class Netflix{

static String Top10Movies[]={"The Idea of You","Road House","Everybody’s Talking About Jamie","Bottoms","Saltburn","The Burial","A Million Miles Away","A Million Miles Away","Shin Masked Rider","Air"};
static String EnglishMovies[]={"12 Angry Men","Anatomy of a Murer","Blow the Man Down","On the Waterfront","The Big Stick","ChinaTown","Schindler's List","ANATOMY OF A MURDER","On the Waterfront","Rear Window","Sound of Metal","A Hero","Psyco","AirPlane","Maverick","Blackklansman","Manchester By the Sea","Paterson" ,"Love n FriendShip","The Saleman","RoseMary's Baby","Once Upon a time in the West","Airplane","BlackKlansman","paterson"};
static String KannadaMovies[]={"Kantara","KGf","Yuvarathna","Rathnan Prapancha","ACT 1978","Ondu Shikariya Kathe","Bheemasena Nalamaharaja","Bheemasena Nalamaharaja","Love Mocktail ","Mayabazar","99","Maara","Dia","Malgudi Days","Soorarari Pottu","Avne Srimannarayana","Cambal","Nanna Prakara","Ondalla Eradalla","French Biriyani","Law","Katheyondu Shuruvaagide","Alidu Ulidavaru","Alidu Ulidavaru","Avane Srimannarayana"};
static String HindiMovies[]={"The Lunchbox","Unpaused","Shikara","Ponniyin Selvan","Dilwale Dulhania Le Jayenge","Section 375","V","Maqbool","Karwaan","Thappad","Newton","Shakuntala Devi","The Ghazi Attack","Bajirao Mastani","Raazi","Mitron","Tumbbad","Sonu Ke Titu Ki Sweety","Gully Boy","Agent Sai Srinivasa Athreya","Batla House","War","Gold","Gold","Baabul"};
static String KoreanSeries[]={"Taxi Driver","Strangers from Hell","Voice","The Doctors","Mr. Queen","Her Private Life","Hotel Del Luna","Doom at your Service","Strong Woman Do Bong Soon ","Welcome to Waikiki","Welcome to Waikiki 2 ","Playful kiss","Secret Garden","True Beauty","Tale of the Nine-Tailed ","The Penthouse","Midnight Café","Flower Boy Next Door","Queen In-Hyun’s Man","Oh My Ghost ","Jumong", "A Witch’s Love","Flower of Evil ","Secret Garden"};


public static void main(String[] ootplatform)
{
	System.out.println("The Top 10 movies of prime is:\n" + Top10Movies[0] + "\n" + Top10Movies[1] + " \n " + Top10Movies[2] + " \n " + Top10Movies[3] + " \n " + Top10Movies[4] + " \n " + Top10Movies[5] + " \n " + Top10Movies[6] + " \n " + Top10Movies[7] + " \n " + Top10Movies[8] + " \n " + Top10Movies[9]  );
	System.out.println("The Top English movies of prime is:\n" + EnglishMovies[0] + "\n" + EnglishMovies[1] + " \n " + EnglishMovies[2] + " \n " + EnglishMovies[3] + " \n " + EnglishMovies[4] + " \n " + EnglishMovies[5] + " \n " + EnglishMovies[6] + " \n " + EnglishMovies[7] + " \n " + EnglishMovies[8] + " \n " + EnglishMovies[9] + " \n " + EnglishMovies[10] + " \n " +  EnglishMovies[11] + " \n " + EnglishMovies[12] + " \n " + EnglishMovies[13] + " \n " + EnglishMovies[14] + " \n " + EnglishMovies[15] + " \n " + EnglishMovies[16] + " \n " + EnglishMovies[17] + " \n " + EnglishMovies[18] + " \n " + EnglishMovies[19] + " \n " + EnglishMovies[20] + " \n " + EnglishMovies[21] + " \n " + EnglishMovies[22] + " \n " + EnglishMovies[23] + " \n " + EnglishMovies[24] );
	System.out.println("The Top Kannada movies of prime is:\n" + KannadaMovies[0] + "\n" + KannadaMovies[1] + " \n " + KannadaMovies[2] + " \n " + KannadaMovies[3] + " \n " + KannadaMovies[4] + " \n " + KannadaMovies[5] + " \n " + EnglishMovies[6] + " \n " + KannadaMovies[7] + " \n " + KannadaMovies[8] + " \n " + KannadaMovies[9] + " \n " + KannadaMovies[10] + " \n " + KannadaMovies[11] + " \n " + KannadaMovies[12] + " \n " + KannadaMovies[13] + " \n " + KannadaMovies[14] + " \n " + KannadaMovies[15] + " \n " + KannadaMovies[16] + " \n " + KannadaMovies[17] + " \n " + KannadaMovies[18] + " \n " + KannadaMovies[19] + " \n " + KannadaMovies[20] + " \n " + KannadaMovies[21] + " \n " + KannadaMovies[22] + " \n " + KannadaMovies[23] + " \n " + KannadaMovies[24] );
	System.out.println("The Top Hindi movies of prime is:\n" + HindiMovies[0] + "\n" + HindiMovies[1] + " \n " + HindiMovies[2] + " \n " + HindiMovies[3] + " \n " + HindiMovies[4] + " \n " + HindiMovies[5] + " \n " + HindiMovies[6] + " \n " + HindiMovies[7] + " \n " + HindiMovies[8] + " \n " + HindiMovies[9] + " \n " + HindiMovies[10] + " \n " + HindiMovies[11] + " \n "+ HindiMovies[12] + " \n " + HindiMovies[13] + " \n " + HindiMovies[14] + " \n " + HindiMovies[15] + " \n " + HindiMovies[16] + " \n " + HindiMovies[17] + " \n " + HindiMovies[18] + " \n " + HindiMovies[19] + " \n " + HindiMovies[20] + " \n " + HindiMovies[21] + " \n " + HindiMovies[22] + " \n " + HindiMovies[23]   );
	System.out.println("The Top Korean movies of prime is:\n" + KoreanSeries[0] + "\n" + KoreanSeries[1] + " \n " + KoreanSeries[2] + " \n " + KoreanSeries[3] + " \n " + KoreanSeries[4] + " \n " + KoreanSeries[5] + " \n " + KoreanSeries[6] + " \n " + KoreanSeries[7] + " \n " + KoreanSeries[8] + " \n " + KoreanSeries[9] + " \n " + KoreanSeries[10] + " \n " + KoreanSeries[11] + " \n "+ KoreanSeries[12] + " \n " + KoreanSeries[13] + " \n " + KoreanSeries[14] + " \n " + KoreanSeries[15] + " \n " + KoreanSeries[16] + " \n " + KoreanSeries[17] + " \n " + KoreanSeries[18] + " \n " + KoreanSeries[19] + " \n " + KoreanSeries[20] + " \n " + KoreanSeries[21] + " \n " + KoreanSeries[22] + " \n " + KoreanSeries[23]  );
	
}
}